---
title: "PinkTutorial"
author: "Jules Hanhart"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install Instructions:
enter the following code into your console of rstudio. 
devtools::install_github("juleshanhart/1hanhart.pkg")


Data being used: surveys dataset
Download Data Instructions: 
enter the following code into your console of rstudio.
read_csv("/cloud/project/hanhart.pkg/data/surveys.csv")


This package will consolidate and condense data, making it easier to look at, and then turn the final plot pink so I like it more.


Function 1: a function to clean data- consolidate function
The consolidate function removes NA values and simultaneously deletes the majority of columns in order to return four "focus" columns. 

Function 2: a function to manipulate data- mutate function
The mutate function converts the data in the weight column from grams to pounds. 

Function 3: a statistical function- lm function
The lm function fits a linear model using plot_id and weight, giving information about residuals, error rates, estimates, etc.

Function 4: a function that plots data - point plot function
The point plot function returns a plot using geom_point(), of weight and species_id grouped by sex. 

Function 5: a function for fun- pink function
The pink function simply turns the colors in the previous graph pink so that I enjoy looking at it more. 

